import type { TextDict } from "@/lib/i18n";

export const REVIEW = {
  // Existing keys from review-form.tsx
  eyebrow: { id: "Latihan Pengulangan", en: "Spaced Review" },
  noEnrollment: { id: "Anda belum terdaftar di kursus mana pun.", en: "You are not enrolled in any course yet." },
  noneDue: { id: "Tidak ada item yang perlu diulang hari ini.", en: "No items due for review today." },
  overdueDays: { id: "{n} hari terlambat", en: "{n} days overdue" },
  dueToday: { id: "Jatuh tempo hari ini", en: "Due today" },
  dueInDays: { id: "Jatuh tempo dalam {n} hari", en: "Due in {n} days" },
  doneNext: { id: "{title} selesai. Ulangan berikutnya: {date}.", en: "{title} done. Next review: {date}." },
  notDue: { id: "Item ini belum jatuh tempo.", en: "This item is not yet due." },
  notScheduled: { id: "Item ini tidak dijadwalkan.", en: "This item is not scheduled." },
  saveFailed: { id: "Gagal menyimpan. Coba lagi.", en: "Failed to save. Please try again." },
  queueSummary: { id: "{n} item perlu diulang dari {course}.", en: "{n} items due for review from {course}." },
  itemAria: { id: "Item ulangan: {title}", en: "Review item: {title}" },
  howWell: { id: "Seberapa baik Anda mengingat ini?", en: "How well do you remember this?" },
  confidenceNotUnderstood: { id: "Belum paham", en: "Not understood" },
  confidenceSomewhat: { id: "Sedikit paham", en: "Somewhat" },
  confidenceOkay: { id: "Cukup", en: "Okay" },
  confidenceUnderstood: { id: "Paham", en: "Understood" },
  confidenceVery: { id: "Sangat paham", en: "Very well" },

  // New keys for question-level review
  title: { id: "Ulangan Ber间隔", en: "Spaced Review" },
  dueForReview: { id: "Perlu diulang", en: "Due for Review" },
  mastered: { id: "Dikuasai", en: "Mastered" },
  avgMastery: { id: "Rata-rata Penguasaan", en: "Avg Mastery" },
  reviewQuestion: { id: "Ulang Pertanyaan", en: "Review Question" },
  howWellDidYouRecall: { id: "Seberapa ingat Anda?", en: "How well did you recall?" },
  submitRating: { id: "Kirim Penilaian", en: "Submit Rating" },
  submitting: { id: "Mengirim...", en: "Submitting..." },
  rateSuccess: { id: "Penilaian berhasil disimpan", en: "Rating saved successfully" },
  rateError: { id: "Gagal menyimpan penilaian", en: "Failed to save rating" },
  noQuestionsForReview: { id: "Tidak ada pertanyaan untuk diulang", en: "No questions to review" },
  reviews: { id: "Ulangan", en: "Reviews" },
  accuracy: { id: "Akurasi", en: "Accuracy" },
  interval: { id: "Interval", en: "Interval" },
  loading: { id: "Memuat...", en: "Loading..." },
  startReview: { id: "Mulai Ulangan", en: "Start Review" },
  nextReview: { id: "Ulangan berikutnya", en: "Next review" },
  daysUntilDue: { id: "{n} hari lagi", en: "{n} days until due" },
  overdue: { id: "Terlambat", en: "Overdue" },
  learning: { id: "Sedang Dipelajari", en: "Learning" },
  newQuestion: { id: "Baru", en: "New" },
  difficulty: { id: "Kesulitan", en: "Difficulty" },
  easy: { id: "Mudah", en: "Easy" },
  medium: { id: "Sedang", en: "Medium" },
  hard: { id: "Sulit", en: "Hard" },
} satisfies TextDict;
